<a href="https://colab.research.google.com/github/prajvarun/FMML_Project_and_Labs/blob/main/basics_of_python_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
#Question 0:#
#write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.#

#string methods
#---------------
#count() method:-
#Returns the number of times a specified value occurs in a string
#example:
txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple")
print(x)
#upper() method:-
#Converts a string into upper case
#example:
txt = "Hello my friends"
x = txt.upper()
print(x)
#find() method:-
#Searches the string for a specified value and returns the position of where it was found
#example:
txt = "Hello, welcome to my world."
x = txt.find("welcome")
print(x)
#-------------------------------------------------------------------------------------------
#list methods
#---------------
#append() method:-
#Adds an element at the end of the list
#example:-
fruits2 = ['apple', 'banana', 'cherry']
fruits2.append("orange")
print(fruits2)
#clear() method:-
#Removes all the elements from the list
#example:-
fruits = ['apple', 'banana', 'cherry', 'orange']
fruits.clear()
print(fruits)
#copy() method:-
#Returns a copy of the list
#example:-
fruits1 = ['apple', 'banana', 'cherry', 'orange']
x = fruits1.copy()
print(fruits1)
#-------------------------------------------------------------------------------------------
#tuple methods
#---------------
#count() method:-
#Returns the number of times a specified value occurs in a tuple
#example:-
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
x = thistuple.count(5)
print(x)
#index() method:-
#Searches the tuple for a specified value and returns the position of where it was found
#example:-
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
x = thistuple.index(8)
print(x)
#------------------------------------------------------------------------------------------
#set methods
#-----------
#add() method:-
#Adds an element to the set
#example:
fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)
#pop() method:-
#Removes an element from the set
#example:-
fruits = {"apple", "banana", "cherry"}
fruits.pop()
print(fruits)
#union() method:-
#Return a set containing the union of sets
#example:-
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.union(y)
print(z)
#-------------------------------------------------------------------------------------------
#dictionary methods
#------------------
#fromkeys() method:-
#Returns a dictionary with the specified keys and value
#example:-
x = ('key1', 'key2', 'key3')
y = 0
thisdict = dict.fromkeys(x, y)
print(thisdict)
#items() method:-
#Returns a list containing a tuple for each key value pair
#example:-
watch = {
  "brand": "titan",
  "model": "Neo Splash Blue Dial Stainless Steel Strap Watch",
  "year": 1964
}
x = watch.items()
print(x)
#popitem() method:-
#Removes the last inserted key-value pair
#example:-
watch = {
  "brand": "titan",
  "model": "Neo Splash Blue Dial Stainless Steel Strap Watch",
  "year": 1964
}
watch.popitem()
print(watch)
#--------------------------------------------------------------------------------------------
#Question 1 :
#Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.

def reverse_and_add_strings(A, B):
    reversestring_A = A[::-1] # Reverse string A
    result =  reversestring_A + B # Concatenation of the reversed string A with the string B

    return result # Returning the result

string_A = "Hello"
string_B = "raj varun"
Final_String = reverse_and_add_strings(string_A, string_B) # The final string
print(Final_String)
#-----------------------------------------------------------------------------------------------------------------------------------
#Question 2 :
#Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.
#work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]

def calculate_pay(work_hours):
    max_hours = 0
    female_worker = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker = name

    if female_worker is not None:
        payment = max_hours * 20
        print(f"The female worker who worked the most hours is {female_worker}")
        print(f"The amount she should be paid is ${payment}")
    else:
        print("No female workers found in the list.")

workhours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'),('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

calculate_pay(workhours)
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Question 3 :
#a)Create a 5x5 matrix of the following form,
#[[1,1]
#[2,2]]
#i.e. each row is increasing and has repetive elements.
#Hint : you can use hstack, vstack etc.

import numpy as np
base_matrix = np.array([[1, 1], [2, 2]])
horizontal_stack = np.hstack([base_matrix] * 3)
vertical_stack = np.vstack([horizontal_stack] * 3)
result_matrix = vertical_stack[:5, :5]
print(result_matrix)

#b) find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)

import numpy as np
A = np.array([[2, 6], [5, 1]])  # Defining matrix A
B = np.array([[3, 2], [4, 9]])  # Defining matrix B

if A.shape[1] == B.shape[0]: # Checking if the dimensions are compatible for multiplication
    C = np.dot(A, B)  # Computing the dot product of two matrices
    print("Matrix C (Dot Product of A and B):\n", C)
else:
    print("Matrix dimensions are not compatible for dot product.")
#------------------------------------------------------------------------------------------------------------


2
HELLO MY FRIENDS
7
['apple', 'banana', 'cherry', 'orange']
[]
['apple', 'banana', 'cherry', 'orange']
2
3
{'cherry', 'orange', 'apple', 'banana'}
{'apple', 'banana'}
{'cherry', 'google', 'microsoft', 'apple', 'banana'}
{'key1': 0, 'key2': 0, 'key3': 0}
dict_items([('brand', 'titan'), ('model', 'Neo Splash Blue Dial Stainless Steel Strap Watch'), ('year', 1964)])
{'brand': 'titan', 'model': 'Neo Splash Blue Dial Stainless Steel Strap Watch'}
olleHraj varun
The female worker who worked the most hours is Penny
The amount she should be paid is $18400
[[1 1 1 1 1]
 [2 2 2 2 2]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [1 1 1 1 1]]
Matrix C (Dot Product of A and B):
 [[30 58]
 [19 19]]
